// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Workify.Api.Workout.Database;

#nullable disable

namespace Workify.Api.Workout.Migrations
{
    [DbContext(typeof(WorkoutDbContext))]
    partial class WorkoutDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("PlanSequence");

            modelBuilder.Entity("ExercisePlan", b =>
                {
                    b.Property<int>("ExercisesId")
                        .HasColumnType("integer");

                    b.Property<int>("PlanId")
                        .HasColumnType("integer");

                    b.HasKey("ExercisesId", "PlanId");

                    b.HasIndex("PlanId");

                    b.ToTable("ExercisePlan");
                });

            modelBuilder.Entity("Workify.Api.Workout.Models.Entities.Abstractions.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BodyPart")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(1023)
                        .HasColumnType("character varying(1023)");

                    b.Property<int>("ExerciseType")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("AllExercises");

                    b.HasDiscriminator<int>("ExerciseType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Workify.Api.Workout.Models.Entities.Abstractions.Plan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValueSql("nextval('\"PlanSequence\"')");

                    NpgsqlPropertyBuilderExtensions.UseSequence(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(1023)
                        .HasColumnType("character varying(1023)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("Workify.Api.Workout.Models.Entities.PredefinedExercise", b =>
                {
                    b.HasBaseType("Workify.Api.Workout.Models.Entities.Abstractions.Exercise");

                    b.HasDiscriminator().HasValue(0);
                });

            modelBuilder.Entity("Workify.Api.Workout.Models.Entities.UserExercise", b =>
                {
                    b.HasBaseType("Workify.Api.Workout.Models.Entities.Abstractions.Exercise");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("Workify.Api.Workout.Models.Entities.PredefinedPlan", b =>
                {
                    b.HasBaseType("Workify.Api.Workout.Models.Entities.Abstractions.Plan");

                    b.ToTable("PredefinedPlans", (string)null);
                });

            modelBuilder.Entity("Workify.Api.Workout.Models.Entities.UserPlan", b =>
                {
                    b.HasBaseType("Workify.Api.Workout.Models.Entities.Abstractions.Plan");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.ToTable("UserPlans", (string)null);
                });

            modelBuilder.Entity("ExercisePlan", b =>
                {
                    b.HasOne("Workify.Api.Workout.Models.Entities.Abstractions.Exercise", null)
                        .WithMany()
                        .HasForeignKey("ExercisesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Workify.Api.Workout.Models.Entities.Abstractions.Plan", null)
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
