services:
  workify-gateway-api:
    build:
      context: .
      dockerfile: ./Workify.Api.Gateway/Dockerfile
    container_name: workify-gateway-api
    ports:
      - "5030:8080"
    depends_on:
      - workify-auth-api
      - workify-workout-api
      - workify-exercise-stat-api
    networks:
      - workify-backend

  workify-rabbitmq:
    image: rabbitmq:management
    ports:
      - "5020:5672"
      - "5021:15672" # Management UI
    networks:
      - workify-backend
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 2s
      timeout: 5s
      retries: 50

  workify-postgres-db:
    image: postgres:latest
    container_name: workify-postgres-db
    ports:
      - "5010:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Admin123!
    networks:
      - workify-backend
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin" ]
      interval: 2s
      timeout: 5s
      retries: 50

  workify-seq:
    image: datalust/seq
    container_name: workify-seq
    ports:
      - "5022:80"
    environment:
      - ACCEPT_EULA=Y
    networks:
      - workify-backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      interval: 2s
      timeout: 5s
      retries: 50

  workify-auth-api:
    build:
      context: .
      dockerfile: ./Workify.Api.Auth/Dockerfile
    container_name: workify-auth-api
    ports:
      - "5011:8080"
    env_file:
      - dev-common.env
      - ./Workify.Api.Auth/dev.env
    depends_on:
      workify-postgres-db:
        condition: service_healthy
      workify-rabbitmq:
        condition: service_healthy
      workify-seq:
        condition: service_healthy
    networks:
      - workify-backend

  workify-exercise-stat-api:
    build:
      context: .
      dockerfile: ./Workify.Api.ExerciseStat/Dockerfile
    container_name: workify-exercise-stat-api
    ports:
      - "5012:8080"
    env_file:
      - dev-common.env
      - ./Workify.Api.ExerciseStat/dev.env
    depends_on:
      workify-postgres-db:
        condition: service_healthy
      workify-rabbitmq:
        condition: service_healthy
      workify-seq:
        condition: service_healthy
    networks:
      - workify-backend

  workify-workout-api:
    build:
      context: .
      dockerfile: ./Workify.Api.Workout/Dockerfile
    container_name: workify-workout-api
    ports:
      - "5013:8080"
    env_file:
      - dev-common.env
      - ./Workify.Api.Workout/dev.env
    depends_on:
      workify-postgres-db:
        condition: service_healthy
      workify-rabbitmq:
        condition: service_healthy
      workify-seq:
        condition: service_healthy
    networks:
      - workify-backend

networks:
  workify-backend:
    driver: bridge
