version: '3.8'
services:
  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Admin123!
    networks:
      - backend

networks:
  backend:
    driver: bridge
