// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Workify.Api.Workout.Database;

#nullable disable

namespace Workify.Api.Workout.Database.Migrations
{
    [DbContext(typeof(WorkoutDbContext))]
    partial class WorkoutDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Workify.Api.Workout.Models.Entities.Abstractions.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BodyPart")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(1023)
                        .HasColumnType("character varying(1023)");

                    b.Property<int>("ExerciseType")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("AllExercises");

                    b.HasDiscriminator<int>("ExerciseType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Workify.Api.Workout.Models.Entities.Abstractions.Plan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(1023)
                        .HasColumnType("character varying(1023)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("Plan");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Workify.Api.Workout.Models.Entities.Abstractions.Relationships.PlanExercise", b =>
                {
                    b.Property<int>("ExerciseId")
                        .HasColumnType("integer");

                    b.Property<int>("PlanId")
                        .HasColumnType("integer");

                    b.HasKey("ExerciseId", "PlanId");

                    b.HasIndex("PlanId");

                    b.ToTable("PlanExercise");

                    b.HasData(
                        new
                        {
                            ExerciseId = 1,
                            PlanId = 1
                        },
                        new
                        {
                            ExerciseId = 2,
                            PlanId = 1
                        },
                        new
                        {
                            ExerciseId = 3,
                            PlanId = 1
                        },
                        new
                        {
                            ExerciseId = 4,
                            PlanId = 1
                        },
                        new
                        {
                            ExerciseId = 1,
                            PlanId = 2
                        },
                        new
                        {
                            ExerciseId = 4,
                            PlanId = 2
                        },
                        new
                        {
                            ExerciseId = 2,
                            PlanId = 3
                        },
                        new
                        {
                            ExerciseId = 3,
                            PlanId = 3
                        });
                });

            modelBuilder.Entity("Workify.Api.Workout.Models.Entities.PredefinedExercise", b =>
                {
                    b.HasBaseType("Workify.Api.Workout.Models.Entities.Abstractions.Exercise");

                    b.HasDiscriminator().HasValue(0);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BodyPart = 5,
                            Name = "Bench press"
                        },
                        new
                        {
                            Id = 2,
                            BodyPart = 8,
                            Name = "Squat"
                        },
                        new
                        {
                            Id = 3,
                            BodyPart = 8,
                            Name = "Deadlift"
                        },
                        new
                        {
                            Id = 4,
                            BodyPart = 1,
                            Name = "Rows"
                        });
                });

            modelBuilder.Entity("Workify.Api.Workout.Models.Entities.UserExercise", b =>
                {
                    b.HasBaseType("Workify.Api.Workout.Models.Entities.Abstractions.Exercise");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("Workify.Api.Workout.Models.Entities.PredefinedPlan", b =>
                {
                    b.HasBaseType("Workify.Api.Workout.Models.Entities.Abstractions.Plan");

                    b.ToTable("PredefinedPlans", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "FBW"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Upper body"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Lower body"
                        });
                });

            modelBuilder.Entity("Workify.Api.Workout.Models.Entities.UserPlan", b =>
                {
                    b.HasBaseType("Workify.Api.Workout.Models.Entities.Abstractions.Plan");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.ToTable("UserPlans", (string)null);
                });

            modelBuilder.Entity("Workify.Api.Workout.Models.Entities.Abstractions.Relationships.PlanExercise", b =>
                {
                    b.HasOne("Workify.Api.Workout.Models.Entities.Abstractions.Exercise", null)
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Workify.Api.Workout.Models.Entities.Abstractions.Plan", null)
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Workify.Api.Workout.Models.Entities.PredefinedPlan", b =>
                {
                    b.HasOne("Workify.Api.Workout.Models.Entities.Abstractions.Plan", null)
                        .WithOne()
                        .HasForeignKey("Workify.Api.Workout.Models.Entities.PredefinedPlan", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Workify.Api.Workout.Models.Entities.UserPlan", b =>
                {
                    b.HasOne("Workify.Api.Workout.Models.Entities.Abstractions.Plan", null)
                        .WithOne()
                        .HasForeignKey("Workify.Api.Workout.Models.Entities.UserPlan", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
